// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDieQ3dG-GIElzzKSAnoV7uz-4MjHHCE4c',
    appId: '1:159534159850:web:434a91eb1495a3d3358493',
    messagingSenderId: '159534159850',
    projectId: 'new-gereja-gpi',
    authDomain: 'new-gereja-gpi.firebaseapp.com',
    storageBucket: 'new-gereja-gpi.firebasestorage.app',
    measurementId: 'G-JHVE6PZDRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwwDTb2z_Wbls4GqfEQuGnRiVkyRsm2q4',
    appId: '1:159534159850:android:47816b7112fef300358493',
    messagingSenderId: '159534159850',
    projectId: 'new-gereja-gpi',
    storageBucket: 'new-gereja-gpi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVTwYzuqJVCsLo8koVnn2pNUF3zVc-kR8',
    appId: '1:159534159850:ios:0557a7540cddcda6358493',
    messagingSenderId: '159534159850',
    projectId: 'new-gereja-gpi',
    storageBucket: 'new-gereja-gpi.firebasestorage.app',
    iosBundleId: 'com.example.gerejaApp2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVTwYzuqJVCsLo8koVnn2pNUF3zVc-kR8',
    appId: '1:159534159850:ios:0557a7540cddcda6358493',
    messagingSenderId: '159534159850',
    projectId: 'new-gereja-gpi',
    storageBucket: 'new-gereja-gpi.firebasestorage.app',
    iosBundleId: 'com.example.gerejaApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDieQ3dG-GIElzzKSAnoV7uz-4MjHHCE4c',
    appId: '1:159534159850:web:989ca1dbf2cce331358493',
    messagingSenderId: '159534159850',
    projectId: 'new-gereja-gpi',
    authDomain: 'new-gereja-gpi.firebaseapp.com',
    storageBucket: 'new-gereja-gpi.firebasestorage.app',
    measurementId: 'G-8LM1RFFHXG',
  );
}
