// Migration: unregister this service worker so that the new
// flutter_service_worker.js (generated by `flutter build web`)
// can take over. Old clients will phase out automatically.

self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", () => {
  self.registration
    .unregister()
    .then(() => self.clients.claim());
});
